#!/bin/bash

USERID=$(id -u)
if [ $USERID -ne 0 ]
then
    echo "please run the script with root access"
    exit 1
else
    echo "you are super user"
fi

for i in $@
do
  echo "package to install: $i"
done
  